### PR TITLE
week 8 and week 9 A

### PR DESCRIPTION
**Pull request by PraveenNarwal**

### CODE REVIEW

**Comment by PraveenNarwal** [comment]
Week 10 assingment is also added @TanishShah37

**Review by TanishShah37 — COMMENTED** [review]
Week 8 - Comments are Missing. Rest Looks FIne

**Review by TanishShah37 — COMMENTED** [review]
Week 10- Host your project. and Format the code Properly

**Review by TanishShah37 — CHANGES_REQUESTED** [review]
Nice to use of Typescript.  Host your project
useMemo. memo needs to be used

**Pull request merged**
